### PR TITLE
180647604 Show student Comments in Report Item Interactive

### PR DESCRIPTION
**Pull request by knowuh**
This PR adds details to the Report Item Interactive:

Summary View shows:
- Initial authored block type counts

Student Answers show:
- Listing of all blockly comments 
- Changes from authored block set

### CODE REVIEW

**Comment by knowuh** [comment]
@dougmartin -- this still needs a tiny bit of cleanup, but its close.

- There are some weird comments from `src/index.tsx` from an early experiment I will get rid of.
- I want to look at adding some documentation for how report item interactives work.

**Comment by dougmartin** [comment]
@knowuh I'll wait to review after you have done the cleanup you want to do.

**Comment by knowuh** [comment]
@dougmartin, I think this is ready. Thank you.

**Review by dougmartin — APPROVED** [review]
Looks good :+1:

**Pull request merged**
